version: '3.9'
# Version de docker compose

services:
  # CONTENEDOR PARA MYSQL
  mysqldb:
    image: mysql:9.0.1
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      # SO ANFITRIÓN : CONTENEDOR
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - node-mysql:/var/lib/mysql

  # CONTENEDOR PARA NODEJS
  backend:
    # con el . indico que el archivo para construir está en la misma carpeta del docker-compose-dev
    build: 
      context: .
      dockerfile: dockerfile.dev
    depends_on:
      - mysqldb
    links:
      - mysqldb
    env_file:
      - ./.env
    ports:
    # SO ANFITRIÓN : CONTENEDOR
      # - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
      - $NODE_DOCKER_PORT:$NODE_DOCKER_PORT
    volumes:
      # ruta actual que será montada en el volumen : ruta de destino dentro del contenedor
      - .:/myBack
    command: [ "npx", "nodemon" , "src/index.js" ]


volumes:
  node-mysql:

#docker-compose genera los contenedores
#docker compose -f docker-compose-dev.yml up //Ejecuta el archivo .yml y construye los contenedores
#al usar nuevamente docker compose up (luego de parar todo) utiliza los contenedores que ya había creado anteriormente

#docker compose down
#elimina todos los contenedores e 'imagenes' que se crearon


#docker compose up --build (build forzará la construcción de las imágenes, para cuando se haga cambios en el código nodejs)